#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowedHeaders: "Origin, Authorization, Content-Type, Accept, cookie, X-Requested-With"
#            allowCredentials: true
#            
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8181"
            allowedMethods: 
              - GET
            allowedHeaders: "*"